### ISSUE TITLE
Typo in file

### ISSUE THREAD

**Issue by ggenot** [sensu-plugins/sensu-plugins-conntrack#2]
Hello,

The is a typo in the script "e" as first char. 

I see that it has been corrected in commit 6b13cb4 but as there is no new tag so "gem install" still install the version 0.0.3 with typo.

could you create a new tag ? for gem install 

Thanks

**Comment by hanynowsky** [comment]
Same for me. It's very annoying.
I checked the file in the repo and it does not have this typo so it gets generated somehwere when the gem gets installed.

**Comment by boutetnico** [comment]
same issue as @ggenot, waiting for a new tag. Thanks

**Comment by eheydrick** [comment]
New release on the way.

**Comment by eheydrick** [comment]
1.0.0 is live on rubygems.
